// <auto-generated />
namespace NTier.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NTierModelsScrumContext : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NTierModelsScrumContext));
        
        string IMigrationMetadata.Id
        {
            get { return "201710241916190_NTier.Models.ScrumContext"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
